        <meta charset="UTF-8">
        <title>Instant Weather</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Instant Weather - Display the current weather of the town of your choice">
        <meta name="keywords" content="Weather, Instant weather, météo, météo instantanée, températures, précipitations, pression, pressure">
        <meta name="author" content="Zanetti Jordan">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />        <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
        <link rel="stylesheet" type="text/css" href="/styles/bsmain.css">